sudo: false
language: rust
cache: cargo

# run builds for all the trains (and more)
rust:
  - 1.13.0
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: CLIPPY=true

before_script:
  - pip install 'travis-cargo<0.2' --user
  - export PATH=$HOME/.local/bin:$PATH

script: sh travis.sh

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
