language: rust

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
- |
    (cd serde && travis-cargo build) &&
    (cd serde && travis-cargo test) &&
    (cd serde && travis-cargo --only nightly test -- --features nightly-testing) &&
    (cd serde_tests && travis-cargo test) &&
    (cd serde_tests && travis-cargo --only nightly test -- --features nightly-testing) &&
    (cd serde_macros && travis-cargo --only nightly test -- --features nightly-testing) &&
    (cd serde_macros && travis-cargo --only nightly bench -- --features nightly-testing) &&
    (cd serde && travis-cargo --only nightly doc) &&
    (cd serde_codegen && travis-cargo --only nightly doc)

after_success:
- scripts/doc-upload.sh
- (cd serde_tests && travis-cargo coveralls --no-sudo)

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
