[package]
name = "serde_macros"
# DO NOT RELEASE ANY MORE 0.7 RELEASES FROM THIS BRANCH
# USE THE 0.7.x BRANCH
version = "0.8.0-rc3"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Macros to auto-generate implementations for the serde framework"
repository = "https://github.com/serde-rs/serde"
documentation = "https://github.com/serde-rs/serde"
keywords = ["serde", "serialization"]
include = ["Cargo.toml", "src/**/*.rs"]

[lib]
name = "serde_macros"
plugin = true

[features]
unstable-testing = ["clippy", "serde/unstable-testing", "serde_codegen/unstable-testing"]

[dependencies]
clippy = { version = "^0.*", optional = true }
serde_codegen = { version = "^0.8.0-rc3", default-features = false, features = ["unstable"] }

[dev-dependencies]
clippy = "^0.*"
compiletest_rs = "^0.2.0"
fnv = "1.0"
rustc-serialize = "^0.3.16"
serde = "0.8.0-rc3"
serde_test = "0.8.0-rc3"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
