[package]
name = "serde_test_suite"
version = "0.0.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>", "David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[features]
unstable = ["serde/unstable"]
versioning = ["serde/versioning-derive", "serde_derive/versioning", "serde_test/versioning"]

[dependencies]
serde = { path = "../serde" }
serde_test = { path = "../serde_test", optional = true }
serde_derive = { path = "../serde_derive", optional = true }

[dev-dependencies]
fnv = "1.0"
rustc-serialize = "0.3.16"
rustversion = "0.1"
serde = { path = "../serde", features = ["rc", "derive"] }
serde_derive = { path = "../serde_derive", features = ["deserialize_in_place"] }
serde_test = { path = "../serde_test" }
trybuild = "1.0"
